version: '3'
services:
  hydro:
    image: zqy123/hydro:latest
    ports:
      - 8080:8080
    links:
      - mongo
    networks:
      - MyNetwork
    working_dir: /root/Hydro
    command: yarn debug --port=8080 --watch
networks:
  MyNetwork:
    
